spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongo:
      host: localhost
      port: 27017
      database: movies_db
---
spring:
  config:
    activate:
      on-profile: non-prod
  data:
    mongo:
      host: localhost
      port: 27017
      database: movies_db
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongo:
      host: localhost
      port: 27017
      database: movies_db
---
logging:
  level:
    root: debug